/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Bowling.glb -o src/components/BowlingModel.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bowling.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[3.167, 0.019, -4.594]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CUBezierCurve010.geometry} material={materials.Pin} />
        <mesh geometry={nodes.CUBezierCurve010_1.geometry} material={materials.Stripe} />
      </group>
      <group position={[-3.421, 0.019, -4.594]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CUBezierCurve009.geometry} material={materials.Pin} />
        <mesh geometry={nodes.CUBezierCurve009_1.geometry} material={materials.Stripe} />
      </group>
      <group position={[-1.164, 0.019, -4.594]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CUBezierCurve008.geometry} material={materials.Pin} />
        <mesh geometry={nodes.CUBezierCurve008_1.geometry} material={materials.Stripe} />
      </group>
      <group position={[1.073, 0.019, -4.594]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CUBezierCurve007.geometry} material={materials.Pin} />
        <mesh geometry={nodes.CUBezierCurve007_1.geometry} material={materials.Stripe} />
      </group>
      <group position={[2.196, 0, -2.989]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CUBezierCurve006.geometry} material={materials.Pin} />
        <mesh geometry={nodes.CUBezierCurve006_1.geometry} material={materials.Stripe} />
      </group>
      <group position={[-2.216, 0, -2.989]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CUBezierCurve005.geometry} material={materials.Pin} />
        <mesh geometry={nodes.CUBezierCurve005_1.geometry} material={materials.Stripe} />
      </group>
      <group position={[0, 0, -2.989]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CUBezierCurve004.geometry} material={materials.Pin} />
        <mesh geometry={nodes.CUBezierCurve004_1.geometry} material={materials.Stripe} />
      </group>
      <group position={[1.073, 0.019, -1.462]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CUBezierCurve003.geometry} material={materials.Pin} />
        <mesh geometry={nodes.CUBezierCurve003_1.geometry} material={materials.Stripe} />
      </group>
      <group position={[-1.164, 0.019, -1.462]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CUBezierCurve002.geometry} material={materials.Pin} />
        <mesh geometry={nodes.CUBezierCurve002_1.geometry} material={materials.Stripe} />
      </group>
      <mesh geometry={nodes.Light2.geometry} material={materials.Light2} position={[0.142, 17.634, 2.597]} rotation={[0, 0, 0.001]} scale={2.712} />
      <mesh geometry={nodes.Light1.geometry} material={materials.Light} position={[18.052, 2.475, 2.597]} rotation={[0, 0, -1.578]} scale={2.712} />
      <mesh geometry={nodes.Bowling_Ball.geometry} material={materials['Bowling Ball']} position={[1.113, 1.017, 3.535]} rotation={[-0.839, 0, 0]} />
      <mesh geometry={nodes.Floor.geometry} material={materials.Floor} scale={[14.122, 9.828, 9.828]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CUBezierCurve001.geometry} material={materials.Pin} />
        <mesh geometry={nodes.CUBezierCurve001_1.geometry} material={materials.Stripe} />
      </group>
    </group>
  )
}

useGLTF.preload('/Bowling.glb')
